Merchant finder
blsrofe/rails_engine pull request #2
Opened 2017-10-03 04:27 UTC by blsrofe

Merchant tests are passing for show and index. The tests are not passing for find and find_all. There is something wrong in the controller that I am not sure how to fix yet.

2017-10-03 21:09 UTC, blsrofe commented
Spec harness is passing now.

2017-10-03 21:25 UTC, erose357 requested changes
I recommend cleaning up the routes file.  Everything else looks great.  Nice job!

2017-10-03 21:25 UTC, erose357 commented on config/routes.rb
> +  namespace :api do
I recommend DRYing up the routes so the name spacing isn't repeated so much.  This is how I started invoices:
  namespace :api do
    namespace :v1 do
      namespace :invoices do
        get '/find', to: 'search#show'
      end
      resources :merchants, only: [:index, :show]
      resources :invoices, only: [:index, :show]
    end
  end
end

2017-10-04 01:57 UTC, blsrofe commented
@erose357 The routes are fixed and invoices are merged in. We will have to figure out which version of serializers we want to use. I'm not sure if it matters or not.

2017-10-04 03:24 UTC, erose357 approved these changes

2017-10-04 03:24 UTC, merged